info:
  name: Microchat Core API (Development)
  artifact: '@project.artifactId@'
  version: '@project.version@'

spring:
  application:
    name: microchat-api
  rabbitmq:
    addresses: amqp://admin:admin@192.168.1.17:5672
  cloud:
    stream:
      bindings:
        subscriptionChannel:
          destination: microchat.topic
        unsubscriptionChannel:
          destination: microchat.topic
        messageChannel:
          destination: microchat.topic
      rabbit:
        bindings:
          subscriptionChannel:
            producer:
              routingKeyExpression: "'microchatSubscriptionChannel'"
          unsubscriptionChannel:
            producer:
              routingKeyExpression: "'microchatUnsubscriptionChannel'"
          messageChannel:
            producer:
              routingKeyExpression: "'microchatMessageChannel'"
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:file:./data/microchat
    driver-class-name: org.h2.Driver
    platform: org.hibernate.dialect.H2Dialect
    username: root
    password:

server:
  port: 8881
  servlet:
    context-path: /api
